name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build binaries
        run: cargo build --release

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: boxes-0.1.0-${{ matrix.os }}
          draft: true
          files: |
            target/release/boxes
            target/release/boxes.exe
          
